### ISSUE TITLE
missing dependnecy

### ISSUE THREAD

**Issue by hrstoyanov** [ericmedvet/evolved-ge#1]
Failed to execute goal on project EvolvedGrammaticalEvolution: Could not resolve dependencies for project it.units.malelab:EvolvedGrammaticalEvolution:jar:1.0-SNAPSHOT: Could not find artifact at.unisalzburg.dbresearch:apted:jar:0.1.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by ericmedvet** [comment]
Correct: the APTED lib is not on the central repo of Maven, nor, as far as I know, elsewhere. You have to manually [download](http://tree-edit-distance.dbresearch.uni-salzburg.at/) it and add to local repository. In NetBeans, this means right-clicking on the jar name (under Dependencies) and click on "Manual install artifact".
