### ISSUE TITLE
[question] where is the hge/whge code?

### ISSUE THREAD

**Issue by hrstoyanov** [ericmedvet/evolved-ge#2]
Your article: "Hierarchical Grammatical Evolution" is not very clear about how the HGE/WHGE works. Where in this codebase should one look for the HGE/WHGE bits

**Comment by ericmedvet** [comment]
The published article is a short version of a longer paper we are going to submit to a journal soon: I agree that it lacks some key details that prevent, currenlty, the implementation of the very same algorithm for the genotype-phenotype mapping. However, in the two classes [`HierarchicalMapper`](https://github.com/ericmedvet/evolved-ge/blob/master/src/main/java/it/units/malelab/ege/ge/mapper/HierarchicalMapper.java) and [`WeightedHierarchicalMapper`](https://github.com/ericmedvet/evolved-ge/blob/master/src/main/java/it/units/malelab/ege/ge/mapper/WeightedHierarchicalMapper.java) you can find, and hopely understand and reproduce/re-implement, the algorithms of GE and WHGE.

**Comment by hrstoyanov** [comment]
Thanks!
